name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run stylua
        uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check .

  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install luacheck
        run: sudo apt-get install -y lua-check
      - name: Run luacheck
        run: luacheck .

  test:
    strategy:
      matrix:
        neovim-version: [ 'stable', 'nightly' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim-version }}
      - name: Prepare plenary
        run: |
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          ln -s "$(pwd)" ~/.local/share/nvim/site/pack/vendor/start
      - name: Prepare treesitter
        run: |
          git clone --depth 1 https://github.com/nvim-treesitter/nvim-treesitter ~/.local/share/nvim/site/pack/vendor/start/nvim-treesitter
      - name: Run tests
        run: scripts/test

  doc-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable
      - name: Run helptags test
        run: nvim --headless --noplugin -Es -c "helptags doc"
